spring:
  application:
    name: churninsight

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/churninsight}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:churnuser}
    password: ${SPRING_DATASOURCE_PASSWORD:churnpass}
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true  # Muestra las queries SQL en consola
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    customer: ${SPRING_CUSTOMER_MAIL:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

ml-service:
  url: ${ML_SERVICE_URL:http://localhost:8000}