name: Docker Image CI

on:
  push:
    branches: [ "main", "infra/163-optimizar-pipeline-ci" ]
    paths: &shared_paths
     - "backend/**"
     - "backend/pom.xml"
     - "backend/Dockerfile"
     - "ml-service/**"
     - "docker-compose.yaml"
     - ".github/workflows/ci-pipeline.yaml"

     - "!docs/**"
     - "!LICENSE"
     - "!**.md"
     - "!**.png"
     - "!**.drawio"
     - "!data-science/notebooks/**"
     - "!data-science/data/**.csv"
     - "!.gitignore"

  pull_request:
    branches: [ "main" ]
    paths: *shared_paths
     
jobs:

  build-and-push:
    runs-on: ubuntu-latest

    permissions: 
      contents: read
      packages: write

    strategy:
      matrix:
        service: [backend, ml-service]

    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lowercase Repository Name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      
      - name: GHCR Login
        uses: docker/login-action@v3
        with:  
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build ${{ matrix.service }}
        run: docker build -t ghcr.io/${{ env.REPO_LC }}/${{ matrix.service }}:latest ./${{ matrix.service }}
          
      - name: push ${{ matrix.service }}
        if: github.event_name != 'pull_request'
        run: docker push ghcr.io/${{ env.REPO_LC }}/${{ matrix.service }}:latest
