name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths: &shared_paths
      # Backend
      - "backend/**"
      - "!backend/target/**"

      # ML
      - "ml-service/**"

      # Frontend
      - "frontend/src/**"
      - "frontend/public/**"
      - "frontend/package.json"
      - "frontend/package-lock.json"
      - "frontend/tsconfig.json"
      - "frontend/vite.config.ts"
      - "frontend/tailwind.config.js"
      - "frontend/postcss.config.js"
      - "frontend/index.html"
      - "frontend/Dockerfile"
      - "frontend/nginx.conf"
      - "!frontend/node_modules/**"
      - "!frontend/dist/**"
      - "!frontend/mock_ups/**"
      - "!frontend/Prompts/**"

      # Infraestructura
      - "docker-compose.yaml"
      - ".github/workflows/ci-pipeline.yaml"

      # Otras Exclusiones
      - "!docs/**"
      - "!agentes/**"
      - "!contracts/**"
      - "!data-science/**"
      - "!infra/**"
      - "!LICENSE"
      - "!**.md"
      - "!**.png"
      - "!**.jpg"
      - "!**.drawio"
      - "!data-science/notebooks/**"
      - "!data-science/data/**.csv"
      - "!.gitignore"

  pull_request:
    branches: ["main"]
    paths: *shared_paths

jobs:
  call-docker-build:
    permissions:
      contents: read
      packages: write

    uses: phylip28/gha-workflows/.github/workflows/docker-ghcr.yaml@main
    with:
      services: '["backend", "ml-service", "frontend"]'
    secrets: inherit
